- hosts: localhost
  tasks:
  - name: Python, virtualenv and docker dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      state: latest
      update_cache: yes
    become: yes

  - name: Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/trusted.gpg.d/ansible-ubuntu-ansible.gpg

  - name: Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Apt and Docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Docker module for python
    pip:
      name: docker
      state: present

  - name: Docker module for python
    pip:
      name: docker-compose
      state: present

  - name: Create airflow user
    user:
      name: airflow
      uid: 50000
      group: root
      system: yes
    become: yes
      
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: airflow
      group: root
      mode: '0755'
    loop:
      - /home/user/airflow_project/dags
      - /home/user/airflow_project/logs
      - /home/user/airflow_project/plugins
      - /home/user/airflow_project/requirements

- hosts: localhost
  vars:
    airflow_proj_dir: .
    tasks:
    - name: Copy airflow folder
      ansible.builtin.copy:
        src: airflow/*
        dest: "{{ airflow_proj_dir }}/dags/"
        mode: '0644'
