- hosts: localhost
  tasks:
  - name: Python, virtualenv and docker dependencies
    apt:
      pkg:
      - python3
      - virtualenv
      - apt-transport-https
      - ca-certificates
      - curl
      - python3-setuptools
      state: latest
      update_cache: yes
    become: yes

  - name: Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/trusted.gpg.d/ansible-ubuntu-ansible.gpg

  - name: Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Apt and Docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Docker module for python
    pip:
      name: docker
      state: present

  - name: Docker module for python
    pip:
      name: docker-compose
      state: present

  - name: Pandas
    pip:
      name: pandas
      state: present

  - name: Pyspark
    pip:
      name: pyspark
      state: present

  - name: Boto3
    pip:
      name: boto3
      state: present

  - name: Google API
    pip:
      name: google-api-python-client
      state: present

  - name: Pytube
    pip:
      name: pytube
      state: present

  - name: Pytest
    pip:
      name: pytest
      state: present

  - name: Unit test
    pip:
      name: unittest2
      state: present

- hosts: localhost
  vars:
    airflow_proj_dir: /home/user/airflow_project
    tasks:
    - name: Copy airflow folder
      ansible.builtin.copy:
        src: airflow/*
        dest: "{{ airflow_proj_dir }}/dags/"
        mode: '0644'
